"""Fix attempts table

Revision ID: cf87594fdd9b
Revises: ab6ab17023e4
Create Date: 2025-12-03 00:08:02.803010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cf87594fdd9b"
down_revision: Union[str, Sequence[str], None] = "ab6ab17023e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attempts", sa.Column("chosen_code", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attempts", "chosen_code")
    # ### end Alembic commands ###
